version: "3.9"

services:
  redis-stream:
    image: redis:6-alpine
    ports:
      - "6379:6379"

  redis-graph:
    image: redislabs/redisgraph:2.8
    ports:
      - "6380:6379"

  psql:
    image: postgres:14-bullseye
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: train_archive
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data/pgdata

volumes:
  pg_data:
